import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { createApp } from '../src/app.js';
import { ApiError } from '../src/service.js';

const uuid='11111111-1111-4111-8111-111111111111';
const config={trustProxyHops:0,allowedOrigins:new Set(['https://app.example']),internalApiToken:'i'.repeat(32),adminApiToken:'a'.repeat(32)};
function fakeService(){return {getRoster:async()=>({activity:{slug:'task-1',title:'T'},classes:[]}),openSession:async()=>({sessionRef:uuid}),sessionDetails:async()=>({sessionRef:uuid,draftVersion:1,sections:[],comments:[],attempts:[]}),saveDraft:async data=>({sessionRef:data.sessionRef,draftVersion:2}),saveResponses:async data=>({sessionRef:data.sessionRef,draftVersion:2,responses:data.responses}),submitCheck:async()=>({attemptRef:uuid,status:'queued'}),publishLive:async()=>({accepted:true}),listLive:async()=>({students:[]}),getAttempt:async()=>({attemptRef:uuid,status:'queued',version:2}),claimJobs:async()=>[],completeJob:async data=>data,failJob:async()=>({}),recoverJobs:async()=>[],retryAttempt:async()=>({attemptRef:uuid,status:'queued'}),retryFailedAttempt:async()=>({attemptRef:uuid,status:'queued'}),reopenSection:async()=>({sessionRef:uuid})};}
function app(service=fakeService(),adminAuth,teacherCommentService=null,lmsResultService=null){return createApp({config,pool:{query:async()=>({rows:[]})},service,adminAuth,teacherCommentService,lmsResultService});}
function appWithProvisional(service=fakeService(),adminAuth){const provisionalService={createStudent:async data=>({studentRef:uuid,displayName:data.displayName,provisional:true,requiresAccessCode:true}),listPending:async()=>[],resetCode:async()=>({studentRef:uuid,accessCode:'2468'}),reconcile:async()=>({reconciliationStatus:'matched'})};return createApp({config,pool:{query:async()=>({rows:[]})},service,provisionalService,adminAuth});}
test('CORS allows PUT and required conditional headers',async()=>{const r=await request(app()).options('/api/v1/sessions/x').set('Origin','https://app.example');assert.equal(r.status,204);assert.match(r.headers['access-control-allow-methods'],/PUT/);assert.match(r.headers['access-control-allow-headers'],/If-None-Match/);});
test('save requires requestId and three draft fields',async()=>{const r=await request(app()).put(`/api/v1/sessions/${uuid}/draft`).send({baseVersion:0});assert.equal(r.status,400);});
test('attempt returns 304 when ETag unchanged',async()=>{const first=await request(app()).get(`/api/v1/attempts/${uuid}`);assert.equal(first.status,200);const second=await request(app()).get(`/api/v1/attempts/${uuid}`).set('If-None-Match',first.headers.etag);assert.equal(second.status,304);});
test('internal job endpoint is Bearer fail-closed',async()=>{assert.equal((await request(app()).post('/api/v1/internal/grading-jobs/claim').send({workerId:'n8n',maxJobs:1,leaseSeconds:420})).status,401);assert.equal((await request(app()).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'n8n',maxJobs:1,leaseSeconds:420})).status,200);});
test('grading claim defaults to Task 1 and can isolate Lesson 13 jobs',async()=>{const service=fakeService();const received=[];service.claimJobs=async data=>{received.push(data);return [];};await request(app(service)).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'task1-grader',maxJobs:1,leaseSeconds:420});await request(app(service)).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'lesson-grader',workerPool:'lesson13',maxJobs:1,leaseSeconds:420});assert.equal(received[0].workerPool,'task1');assert.equal(received[1].workerPool,'lesson13');});
test('grading claim accepts batches larger than the former four-job cap',async()=>{const service=fakeService();let received;service.claimJobs=async data=>{received=data;return [];};const response=await request(app(service)).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'n8n',maxJobs:40,leaseSeconds:420});assert.equal(response.status,200);assert.equal(received.maxJobs,40);});
test('conflict exposes current server draft',async()=>{const service=fakeService();service.saveDraft=async()=>{throw new ApiError(409,'DRAFT_VERSION_CONFLICT','X',{current:{draftVersion:4}});};const r=await request(app(service)).put(`/api/v1/sessions/${uuid}/draft`).send({baseVersion:0,requestId:uuid,overview:'o',body1:'b',body2:''});assert.equal(r.status,409);assert.equal(r.body.current.draftVersion,4);});
test('blank content is stopped before a grading job is created',async()=>{const service=fakeService();let calls=0;service.submitCheck=async()=>{calls+=1;return {attemptRef:uuid,status:'queued'};};const overview=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'overview',requestId:uuid,snapshot:{overview:' \u200B ',body1:'',body2:''}});assert.equal(overview.status,400);assert.equal(calls,0);const outline=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'outline',requestId:uuid,snapshot:{overview:'',body1:'Body 1',body2:''}});assert.equal(outline.status,202);assert.equal(calls,1);});
test('Draft requires both Draft 1 and Draft 2 before the service is called',async()=>{const service=fakeService();let calls=0;service.submitCheck=async()=>{calls+=1;return {attemptRef:uuid,status:'queued'};};const blankDraft2=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'draft',requestId:uuid,snapshot:{overview:'Overview',body1:'Body 1',body2:'Body 2',draft1:'Draft 1',draft2:' \u200B '}});assert.equal(blankDraft2.status,400);assert.equal(calls,0);const complete=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'draft',requestId:uuid,snapshot:{overview:'Overview',body1:'Body 1',body2:'Body 2',draft1:'Draft 1',draft2:'Draft 2'}});assert.equal(complete.status,202);assert.equal(calls,1);});
test('n8n complete contract accepts status and normalizes resultStatus',async()=>{const service=fakeService();let received;service.completeJob=async data=>{received=data;return data;};const r=await request(app(service)).post(`/api/v1/internal/grading-jobs/${uuid}/complete`).set('Authorization',`Bearer ${config.internalApiToken}`).send({leaseToken:uuid,status:'passed',feedback:'👍 Đã đạt.',rawModelMeta:{modelId:'test'}});assert.equal(r.status,200);assert.equal(received.resultStatus,'passed');});
test('technical failure can be retried through the public opaque attempt reference',async()=>{const r=await request(app()).post(`/api/v1/attempts/${uuid}/retry`).send({});assert.equal(r.status,202);assert.equal(r.body.attempt.status,'queued');});
test('Lesson 13 saves a dynamic response map with optimistic versioning',async()=>{const r=await request(app()).put(`/api/v1/lesson-sessions/${uuid}/responses`).send({baseVersion:0,requestId:uuid,responses:{body1_idea1:'Idea'}});assert.equal(r.status,200);assert.equal(r.body.session.responses.body1_idea1,'Idea');});
test('Lesson live dashboard is fail-closed without teacher authentication',async()=>{const r=await request(app()).get('/api/v1/admin/live/activities/writing-lesson13-young-leaders');assert.equal(r.status,503);});
test('Authenticated teacher can load the full lesson session with Comment timeline',async()=>{const service=fakeService();service.sessionDetails=async()=>({sessionRef:uuid,comments:[{section:'body1_topic',commentNumber:1,feedback:'Cần sửa'}]});const adminAuth=(q,_r,next)=>{q.reviewer={email:'reviewer@example.invalid'};next();};const r=await request(app(service,adminAuth)).get(`/api/v1/admin/live/lesson-sessions/${uuid}`);assert.equal(r.status,200);assert.equal(r.body.session.comments[0].feedback,'Cần sửa');});
test('Teacher viewer can read every dashboard class but cannot mutate student state',async()=>{const service=fakeService();const adminAuth=(q,_r,next)=>{q.reviewer={email:'viewer@example.invalid',canManage:false};next();};const dashboard=await request(app(service,adminAuth)).get('/api/v1/admin/live/activities/writing-lesson13-young-leaders');assert.equal(dashboard.status,200);assert.equal(dashboard.body.permissions.canManage,false);const retry=await request(app(service,adminAuth)).post(`/api/v1/admin/attempts/${uuid}/retry`).send({});assert.equal(retry.status,403);assert.equal(retry.body.error,'MANAGE_PERMISSION_REQUIRED');});
test('Teacher manager can requeue the same failed AI attempt through an authenticated route',async()=>{const service=fakeService();let received;service.retryFailedAttempt=async data=>{received=data;return {attemptRef:data.attemptRef,status:'queued'};};const adminAuth=(q,_r,next)=>{q.reviewer={email:'reviewer@example.invalid',canManage:true};next();};const r=await request(app(service,adminAuth)).post(`/api/v1/admin/attempts/${uuid}/retry`).send({});assert.equal(r.status,202);assert.equal(r.body.attempt.status,'queued');assert.equal(received.attemptRef,uuid);assert.equal(received.actorRef,'reviewer@example.invalid');});
test('Comment giảng viên là luồng riêng: học viên chỉ xem và trả lời, không có route xóa hay chấp thuận',async()=>{let reply;const comments={list:async()=>({threads:[{threadRef:uuid,messages:[]}],version:'v1'}),reply:async data=>{reply=data;return {threadRef:uuid,messages:[]};}};const listed=await request(app(fakeService(),undefined,comments)).get(`/api/v1/sessions/${uuid}/teacher-comments`);assert.equal(listed.status,200);assert.match(listed.headers.etag,/teacher-comments-v1/);const answered=await request(app(fakeService(),undefined,comments)).post(`/api/v1/sessions/${uuid}/teacher-comments/${uuid}/replies`).send({body:'Em đã hiểu.',requestId:uuid});assert.equal(answered.status,201);assert.equal(reply.actorRole,'student');assert.equal(reply.sessionRef,uuid);assert.equal((await request(app(fakeService(),undefined,comments)).delete(`/api/v1/sessions/${uuid}/teacher-comments/${uuid}`)).status,404);});
test('Draft result route chỉ trả dữ liệu đã qua dịch vụ proxy',async()=>{const lms={getDraftResult:async({sessionRef})=>({essays:[{id:'one'}],updatedAt:'2026-08-18T01:00:00.000Z',sessionRef})};const r=await request(app(fakeService(),undefined,null,lms)).get(`/api/v1/sessions/${uuid}/draft-result`);assert.equal(r.status,200);assert.equal(r.body.result.essays.length,1);assert.equal(r.body.result.sessionRef,uuid);});
test('Mọi giảng viên đã xác minh đều được tạo, trả lời và đánh dấu xử lý nhưng comment vẫn được trả về',async()=>{const calls=[];const comments={create:async data=>{calls.push(['create',data]);return {threadRef:uuid,status:'open'};},reply:async data=>{calls.push(['reply',data]);return {threadRef:uuid,status:'open'};},setStatus:async data=>{calls.push(['status',data]);return {threadRef:uuid,status:data.status};},list:async()=>({threads:[],version:'v1'})};const adminAuth=(q,_r,next)=>{q.reviewer={email:'teacher@example.invalid',canManage:false};next();};const created=await request(app(fakeService(),adminAuth,comments)).post(`/api/v1/admin/live/sessions/${uuid}/teacher-comments`).send({sectionKey:'overview',fieldKey:'overview',start:0,end:4,baseVersion:2,body:'Cần viết rõ hơn.',requestId:uuid});assert.equal(created.status,201);const replied=await request(app(fakeService(),adminAuth,comments)).post(`/api/v1/admin/teacher-comments/${uuid}/replies`).send({body:'Thầy bổ sung.',requestId:uuid});assert.equal(replied.status,201);const addressed=await request(app(fakeService(),adminAuth,comments)).post(`/api/v1/admin/teacher-comments/${uuid}/status`).send({status:'addressed',requestId:uuid});assert.equal(addressed.status,200);assert.deepEqual(calls.map(item=>item[0]),['create','reply','status']);assert.equal(calls[0][1].actorRef,'teacher@example.invalid');});
test('Lesson presence heartbeat accepts only an opaque session and field key',async()=>{const r=await request(app()).put(`/api/v1/lesson-sessions/${uuid}/live`).send({activeField:'body1_idea1'});assert.equal(r.status,200);assert.equal(r.body.accepted,true);});
test('học viên tạm chỉ được tạo với tên hợp lệ và mã đúng bốn số',async()=>{const invalid=await request(appWithProvisional()).post('/api/v1/activities/task-1/provisional-students').send({classRef:uuid,displayName:'Học viên mới',pin:'12ab',requestId:uuid});assert.equal(invalid.status,400);const valid=await request(appWithProvisional()).post('/api/v1/activities/task-1/provisional-students').send({classRef:uuid,displayName:'Học viên mới',pin:'2468',requestId:uuid});assert.equal(valid.status,201);assert.equal(valid.body.student.provisional,true);assert.equal(Object.hasOwn(valid.body.student,'pin'),false);});
test('mã truy cập hồ sơ tạm được chuyển tới service nhưng không xuất hiện trong response',async()=>{const service=fakeService();let received;service.openSession=async data=>{received=data;return {sessionRef:uuid};};const response=await request(appWithProvisional(service)).post('/api/v1/sessions').send({activitySlug:'task-1',classRef:uuid,studentRef:uuid,accessCode:'2468'});assert.equal(response.status,201);assert.equal(received.accessCode,'2468');assert.equal(JSON.stringify(response.body).includes('2468'),false);});
test('đặt lại mã và đối soát luôn fail-closed nếu chưa đăng nhập giảng viên',async()=>{assert.equal((await request(appWithProvisional()).post(`/api/v1/admin/provisional-students/${uuid}/reset-code`)).status,503);assert.equal((await request(appWithProvisional()).post(`/api/v1/admin/provisional-students/${uuid}/reconcile`).send({officialStudentRef:uuid})).status,503);});
