import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { createApp } from '../src/app.js';
import { ApiError } from '../src/service.js';

const uuid='11111111-1111-4111-8111-111111111111';
const config={trustProxyHops:0,allowedOrigins:new Set(['https://app.example']),internalApiToken:'i'.repeat(32),adminApiToken:'a'.repeat(32)};
function fakeService(){return {getRoster:async()=>({activity:{slug:'task-1',title:'T'},classes:[]}),openSession:async()=>({sessionRef:uuid}),sessionDetails:async()=>({sessionRef:uuid,draftVersion:1,sections:[],comments:[],attempts:[]}),saveDraft:async data=>({sessionRef:data.sessionRef,draftVersion:2}),saveResponses:async data=>({sessionRef:data.sessionRef,draftVersion:2,responses:data.responses}),submitCheck:async()=>({attemptRef:uuid,status:'queued'}),publishLive:async()=>({accepted:true}),listLive:async()=>({students:[]}),getAttempt:async()=>({attemptRef:uuid,status:'queued',version:2}),claimJobs:async()=>[],completeJob:async data=>data,failJob:async()=>({}),recoverJobs:async()=>[],retryAttempt:async()=>({attemptRef:uuid,status:'queued'}),retryFailedAttempt:async()=>({attemptRef:uuid,status:'queued'}),reopenSection:async()=>({sessionRef:uuid})};}
function app(service=fakeService(),adminAuth){return createApp({config,pool:{query:async()=>({rows:[]})},service,adminAuth});}
test('CORS allows PUT and required conditional headers',async()=>{const r=await request(app()).options('/api/v1/sessions/x').set('Origin','https://app.example');assert.equal(r.status,204);assert.match(r.headers['access-control-allow-methods'],/PUT/);assert.match(r.headers['access-control-allow-headers'],/If-None-Match/);});
test('save requires requestId and three draft fields',async()=>{const r=await request(app()).put(`/api/v1/sessions/${uuid}/draft`).send({baseVersion:0});assert.equal(r.status,400);});
test('attempt returns 304 when ETag unchanged',async()=>{const first=await request(app()).get(`/api/v1/attempts/${uuid}`);assert.equal(first.status,200);const second=await request(app()).get(`/api/v1/attempts/${uuid}`).set('If-None-Match',first.headers.etag);assert.equal(second.status,304);});
test('internal job endpoint is Bearer fail-closed',async()=>{assert.equal((await request(app()).post('/api/v1/internal/grading-jobs/claim').send({workerId:'n8n',maxJobs:1,leaseSeconds:420})).status,401);assert.equal((await request(app()).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'n8n',maxJobs:1,leaseSeconds:420})).status,200);});
test('grading claim defaults to Task 1 and can isolate Lesson 13 jobs',async()=>{const service=fakeService();const received=[];service.claimJobs=async data=>{received.push(data);return [];};await request(app(service)).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'task1-grader',maxJobs:1,leaseSeconds:420});await request(app(service)).post('/api/v1/internal/grading-jobs/claim').set('Authorization',`Bearer ${config.internalApiToken}`).send({workerId:'lesson-grader',workerPool:'lesson13',maxJobs:1,leaseSeconds:420});assert.equal(received[0].workerPool,'task1');assert.equal(received[1].workerPool,'lesson13');});
test('conflict exposes current server draft',async()=>{const service=fakeService();service.saveDraft=async()=>{throw new ApiError(409,'DRAFT_VERSION_CONFLICT','X',{current:{draftVersion:4}});};const r=await request(app(service)).put(`/api/v1/sessions/${uuid}/draft`).send({baseVersion:0,requestId:uuid,overview:'o',body1:'b',body2:''});assert.equal(r.status,409);assert.equal(r.body.current.draftVersion,4);});
test('blank content is stopped before a grading job is created',async()=>{const service=fakeService();let calls=0;service.submitCheck=async()=>{calls+=1;return {attemptRef:uuid,status:'queued'};};const overview=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'overview',requestId:uuid,snapshot:{overview:' \u200B ',body1:'',body2:''}});assert.equal(overview.status,400);assert.equal(calls,0);const outline=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'outline',requestId:uuid,snapshot:{overview:'',body1:'Body 1',body2:''}});assert.equal(outline.status,202);assert.equal(calls,1);});
test('Draft requires both Draft 1 and Draft 2 before the service is called',async()=>{const service=fakeService();let calls=0;service.submitCheck=async()=>{calls+=1;return {attemptRef:uuid,status:'queued'};};const blankDraft2=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'draft',requestId:uuid,snapshot:{overview:'Overview',body1:'Body 1',body2:'Body 2',draft1:'Draft 1',draft2:' \u200B '}});assert.equal(blankDraft2.status,400);assert.equal(calls,0);const complete=await request(app(service)).post(`/api/v1/sessions/${uuid}/checks`).send({section:'draft',requestId:uuid,snapshot:{overview:'Overview',body1:'Body 1',body2:'Body 2',draft1:'Draft 1',draft2:'Draft 2'}});assert.equal(complete.status,202);assert.equal(calls,1);});
test('n8n complete contract accepts status and normalizes resultStatus',async()=>{const service=fakeService();let received;service.completeJob=async data=>{received=data;return data;};const r=await request(app(service)).post(`/api/v1/internal/grading-jobs/${uuid}/complete`).set('Authorization',`Bearer ${config.internalApiToken}`).send({leaseToken:uuid,status:'passed',feedback:'👍 Đã đạt.',rawModelMeta:{modelId:'test'}});assert.equal(r.status,200);assert.equal(received.resultStatus,'passed');});
test('technical failure can be retried through the public opaque attempt reference',async()=>{const r=await request(app()).post(`/api/v1/attempts/${uuid}/retry`).send({});assert.equal(r.status,202);assert.equal(r.body.attempt.status,'queued');});
test('Lesson 13 saves a dynamic response map with optimistic versioning',async()=>{const r=await request(app()).put(`/api/v1/lesson-sessions/${uuid}/responses`).send({baseVersion:0,requestId:uuid,responses:{body1_idea1:'Idea'}});assert.equal(r.status,200);assert.equal(r.body.session.responses.body1_idea1,'Idea');});
test('Lesson live dashboard is fail-closed without teacher authentication',async()=>{const r=await request(app()).get('/api/v1/admin/live/activities/writing-lesson13-young-leaders');assert.equal(r.status,503);});
test('Teacher can requeue the same failed AI attempt through an authenticated route',async()=>{const service=fakeService();let received;service.retryFailedAttempt=async data=>{received=data;return {attemptRef:data.attemptRef,status:'queued'};};const adminAuth=(q,_r,next)=>{q.reviewer={email:'reviewer@example.invalid'};next();};const r=await request(app(service,adminAuth)).post(`/api/v1/admin/attempts/${uuid}/retry`).send({});assert.equal(r.status,202);assert.equal(r.body.attempt.status,'queued');assert.equal(received.attemptRef,uuid);assert.equal(received.actorRef,'reviewer@example.invalid');});
test('Lesson presence heartbeat accepts only an opaque session and field key',async()=>{const r=await request(app()).put(`/api/v1/lesson-sessions/${uuid}/live`).send({activeField:'body1_idea1'});assert.equal(r.status,200);assert.equal(r.body.accepted,true);});
